### ISSUE TITLE
Doesn't compile on Linux

### ISSUE THREAD

**Issue by peterazmanov** [jherico/Vulkan#4]
In `base/vulkanContext.hpp` command pool is defined under ifdef for linux platform:

`thread_local vk::CommandPool cmdPool;`

But all other code uses `s_cmdPool` (without ifdefs) which is defined for win32...

**Comment by jherico** [comment]
I'm in the process of fixing all the Linux buld blockers.  I will have a new commit shortly.  Just trying to resolve some GLFW version issues.

**Comment by jherico** [comment]
All of the core compilation issues should be resolved (header file case sensitivity, xcb references, the bad command pool declaration, etc).  

I still have some issues with the GLFW dependency which I'm having trouble solving, so I'm getting linker failures on Linux now, but I'll open another issue for that.

**Comment by peterazmanov** [comment]
What about initialization for linux in vulkanExampleBase.cpp? In upstream repo there was special member for that `initxcbConnection`, in your version initialization is empty. Is it ok? I'm not familiar with XCB or X11.

**Comment by peterazmanov** [comment]
Sorry didn't see your changes related to GLFW. XCB is to be replaced by GLFW, which can handle both linux and win32?

**Comment by jherico** [comment]
That's the idea.  I haven't been able to get a proper build on Linux yet
because of the GLFW stuff.  Ubuntu 16.04 only includes GLFW 3.1, and this
code needs 3.2.  Trying to build GLFW as an external project hasn't worked
so far for me.  Plus, I'm doing all this in a VM, so I can't actually test
running the examples, only building.
